chapter01を追加しました
onolab-tmu/asp-tutorial-2022 pull request #1
Opened 2022-06-13 07:17 UTC by sogyoten

2022-06-16 01:26 UTC, taishi-n requested changes
概ね良いですが，少しだけ修正をお願いします．

2022-06-16 01:26 UTC, taishi-n commented on knishida/chapter01/02.py
> +writefilename = "./knishida/chapter01/02_out.wav"
このように local 環境の絶対パスで書くと他の人が再現でいないので避けましょう．
相対パスで書き直してください．他のファイルも同様です．

2022-06-19 17:02 UTC, sogyoten commented
遅くなりましたが修正しました。
お時間あるときに確認いただければと思います。

2022-06-20 04:50 UTC, taishi-n approved these changes
OKです！

2022-06-20 04:50 UTC, merged