１章を追加
onolab-tmu/asp-tutorial-2022 pull request #7
Opened 2022-06-16 07:02 UTC by dksuga11

2022-06-16 07:25 UTC, taishi-n requested changes

2022-06-16 07:25 UTC, taishi-n commented on dsugawara/chapter01/09.py
> +#print(str(len(white_noise)))
動作確認のためだけのコメントアウトは消すようにしておきましょう．

2022-06-16 07:25 UTC, taishi-n commented on dsugawara/chapter01/09.py
> +#print(str(len(white_noise)))
他は問題ないので少しだけ修正お願いします！

2022-06-20 04:26 UTC, dksuga11 commented on dsugawara/chapter01/09.py
> +#print(str(len(white_noise)))
ありがとうございます！

2022-06-20 04:57 UTC, taishi-n commented on dsugawara/chapter01/09.py
> +#print(str(len(white_noise)))
@dksuga11 修正を commit して pull request に反映するようにお願いします 🙇

2022-06-24 06:56 UTC, dksuga11 commented
@taishi-n 
一章を修正しました

2022-06-24 07:08 UTC, taishi-n approved these changes
OKです！

2022-06-24 07:08 UTC, merged